name: Deploy Bicep files

trigger:
- main

variables:
  resourceGroupName: 'rg-bicep-demo-0023'
  location: 'westeurope'
  webAppName: 'bicep0023'
  templateFile: '01-bicep-webapp/webapp-linux.bicep'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: preDeploy
  jobs:
  - job: scanWhatif
    displayName: scan and run whatif
    pool:
      vmImage: 'windows-2022'

    steps:
    
    - task: RunARMTTKTests@1
      displayName: Scan Bicep files
      inputs:
        templatelocation: '$(templateFile)'
        resultLocation: $(System.DefaultWorkingDirectory)\results
        allTemplatesMain: false
        cliOutputResults: true
        ignoreExitCode: true

    - task: PublishTestResults@2
      displayName: Publish Results
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
      condition: always()

    - task: AzureCLI@2
      displayName: Preview Bicep Changes
      inputs:
        azureSubscription: 'Microsoft-Azure-0(17b12858-3960-4e6f-a663-a06fdae23428)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az --version
          az group create --name $(resourceGroupName) --location $(location)
          az deployment group what-if --resource-group $(resourceGroupName) \
            --template-file $(templateFile) \
            --parameters webAppName=$(webAppName)

- stage: deployBicep
  jobs:
  - job: deployAzure
    displayName: deploy bicep to Azure
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@2
      displayName: Deploy Bicep To Azure
      inputs:
        azureSubscription: 'Microsoft-Azure-0(17b12858-3960-4e6f-a663-a06fdae23428)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --resource-group $(resourceGroupName) \
            --template-file $(templateFile) \
            --parameters webAppName=$(webAppName)
