# This is a basic workflow to help you get started with Actions

name: Deploy-Azure-Bicep-1-job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-bicep-github-acctions
  WEBAPP_NAME: bicep-029

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  preview-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Azure CLI Action
        uses: Azure/cli@v1.0.6
        with:
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: 2.34.1 # optional, default is agentazcliversion
          # Specify the script here
          inlineScript: |
            az version
            az group create -n $RESOURCE_GROUP -l westeurope

      - name: deployment-what-if
        uses: Azure/deployment-what-if-action@v1.0.0
        with:
          # Subscription ID
          subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
          # Resource group name
          resourceGroup: $RESOURCE_GROUP
          # ARM template or Bicep file
          templateFile: 01-bicep-webapp/webapp-linux.bicep
          # Parameters file for the ARM template or Bicep
          # parametersFile: # optional
          # Additional parameters to be applied on the ARM template or Bicep. Multiple parameters should be separated by spaces.
          additionalParameters: webAppName='$WEBAPP_NAME' # optional
          
      
